export const NEW_CONTACT_REQUEST = "NEW_CONTACT_REQUEST";
export const NEW_CONTACT_SUCCESS = "NEW_CONTACT_SUCCESS";
export const NEW_CONTACT_FAIL = "NEW_CONTACT_FAIL";
export const NEW_CONTACT_RESET = "NEW_CONTACT_RESET";

export const ALL_CONTACT_REQUEST = "ALL_CONTACT_REQUEST";
export const ALL_CONTACT_SUCCESS = "ALL_CONTACT_SUCCESS";
export const ALL_CONTACT_FAIL = "ALL_CONTACT_FAIL";
