export const NEW_CONTACT_REQUEST = "NEW_CONTACT_REQUEST";
export const NEW_CONTACT_SUCCESS = "NEW_CONTACT_SUCCESS";
export const NEW_CONTACT_FAIL = "NEW_CONTACT_FAIL";
export const NEW_CONTACT_RESET = "NEW_CONTACT_RESET";

export const ALL_CONTACT_REQUEST = "ALL_CONTACT_REQUEST";
export const ALL_CONTACT_SUCCESS = "ALL_CONTACT_SUCCESS";
export const ALL_CONTACT_FAIL = "ALL_CONTACT_FAIL";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";
export const DELETE_CONTACT_RESET = "DELETE_CONTACT_RESET";

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL";
export const UPDATE_CONTACT_RESET = "UPDATE_CONTACT_RESET";
