export const NEW_NEWS_REQUEST = "NEW_NEWS_REQUEST";
export const NEW_NEWS_SUCCESS = "NEW_NEWS_SUCCESS";
export const NEW_NEWS_FAIL = "NEW_NEWS_FAIL";
export const NEW_NEWS_RESET = "NEW_NEWS_RESET";

export const ALL_NEWS_REQUEST = "ALL_NEWS_REQUEST";
export const ALL_NEWS_SUCCESS = "ALL_NEWS_SUCCESS";
export const ALL_NEWS_FAIL = "ALL_NEWS_FAIL";

export const SINGLE_NEWS_REQUEST = "SINGLE_NEWS_REQUEST";
export const SINGLE_NEWS_SUCCESS = "SINGLE_NEWS_SUCCESS";
export const SINGLE_NEWS_FAIL = "SINGLE_NEWS_FAIL";
export const SINGLE_NEWS_RESET = "SINGLE_NEWS_RESET";

export const DELETE_NEWS_REQUEST = "DELETE_NEWS_REQUEST";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAIL = "DELETE_NEWS_FAIL";
export const DELETE_NEWS_RESET = "DELETE_NEWS_RESET";
