export const ALL_PHOTO_REQUEST = "ALL_PHOTO_REQUEST";
export const ALL_PHOTO_SUCCESS = "ALL_PHOTO_SUCCESS";
export const ALL_PHOTO_FAIL = "ALL_PHOTO_FAIL";

export const UPLOAD_PHOTO_REQUEST = "UPLOAD_PHOTO_REQUEST";
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
export const UPLOAD_PHOTO_FAIL = "UPLOAD_PHOTO_FAIL";
export const UPLOAD_PHOTO_RESET = "UPLOAD_PHOTO_RESET";

export const NEW_PHOTO_REQUEST = "NEW_PHOTO_REQUEST";
export const NEW_PHOTO_SUCCESS = "NEW_PHOTO_SUCCESS";
export const NEW_PHOTO_FAIL = "NEW_PHOTO_FAIL";
export const NEW_PHOTO_RESET = "NEW_PHOTO_RESET";

export const DELETE_PHOTO_REQUEST = "DELETE_PHOTO_REQUEST";
export const DELETE_PHOTO_SUCCESS = "DELETE_PHOTO_SUCCESS";
export const DELETE_PHOTO_FAIL = "DELETE_PHOTO_FAIL";
export const DELETE_PHOTO_RESET = "DELETE_PHOTO_RESET";
